# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProjectPosts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProjectPosts
pod 'SwiftLint'
pod 'SnapKit', '~> 5.6.0'

end
